# Generated by Django 5.1.15 on 2026-08-24 19:55

import apps.events.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('event_type', models.CharField(choices=[('mariage', 'Mariage'), ('portrait', 'Portrait'), ('corporate', 'Corporate'), ('famille', 'Famille'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('is_paid', models.BooleanField(default=False, verbose_name='payé')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='date de paiement')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'expiration")),
                ('is_disabled', models.BooleanField(default=False, verbose_name='désactivé manuellement')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vues')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='nombre de téléchargements')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.events.models.event_photo_upload_path, verbose_name='image')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='nom de fichier original')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'import")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.events.models.generate_token, max_length=64, unique=True, verbose_name='token')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='events.event')),
            ],
        ),
    ]
