# Generated by Django 5.1.15 on 2026-08-24 19:55

import apps.accounts.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name="nom de l'entreprise")),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('public_contact_email', models.EmailField(blank=True, help_text="Affiché au client (ex : page de lien expiré). Laisser vide pour utiliser l'e-mail de connexion.", max_length=254, verbose_name='e-mail de contact public')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='studio_logos/', verbose_name='logo du studio')),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrateur')),
                ('is_photographer', models.BooleanField(default=False, verbose_name='photographe')),
                ('is_active', models.BooleanField(default=True, verbose_name='compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin Django')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.CustomUserManager()),
            ],
        ),
    ]
